modue fdt_top(
    input               clk_fdt                     ,
    input               rstn_fdt                    ,
    input               ckl_sys                     ,
    input               rstn_sys                    ,

    input [11:0]        adc0_data_in                ,
    input               adc_data_in_vld             ,
    input [4:0]         fdt_therm_comp_one_hot      ,
    input [15:0]        fdtmem_addr                 ,
    input               fdtmem_rd                   ,
    input [15:0]        fdtmem_wdata                ,
    input               fdtmem_wr                   ,

    input [2:0]         rg_amp_therm_comp_ratio_0   ,
    input [2:0]         rg_amp_therm_comp_ratio_1   ,
    input [2:0]         rg_amp_therm_comp_ratio_2   ,
    input [2:0]         rg_amp_therm_comp_ratio_3   ,
    input [2:0]         rg_amp_therm_comp_ratio_4   ,
    input [2:0]         rg_amp_data_ratio           ,
    input               rg_fifo_empty_dummy_en      ,
    input               rg_fdt_cache_spi_rw_en      ,
    input               rg_fdt_coef_spi_rw_en       ,
    input               rg_fdt_wait_up              ,
    input               rg_fdt_wait_down            ,
    input               rg_fdt_auto_exit_en         ,
    input               rg_fdt_soft_clr             ,
    input               rg_fdt_en                   ,
    input               rg_fdt_iq_calc_en           ,

    input [2:0]         rg_nn_ilayer_ih_data_ratio  ,
    input [2:0]         rg_nn_ilayer_hh_data_ratio  ,
    input [2:0]         rg_nn_hlayer_ih_data_ratio  ,
    input [2:0]         rg_nn_hlayer_hh_data_ratio  ,
    input [2:0]         rg_nn_flayer_data_ratio     ,
    /* 配置信号 */
    input               rg_label_seq_init_en        ,
    input               rg_label_dec_mode           ,   // 决策模式，0：MemSeq，1：C
    input [4:0]         rg_label_up_memcnt_th       ,   // Count决策模式的up计数阈值
    input [4:0]         rg_label_dn_memcnt_th       ,   // Count决策模式的down计数阈
    input [3:0]         rg_label_memseq_len         ,   // MemSeq长度

    /* FDT检测结果 */
    output logic        ro_fdt_result_up            ,
    output logic        ro_fdt_result_down          ,
    output logic        amp_iq_vld_to_fifo_sys      ,
    output logic [11:0] amp_iq_data_to_fifo_sys

);

fdt_ctrl fdt_ctrl_inst(
    .clk_fdt                  ( clk_fdt                 ),
    .rstn_fdt                 ( rstn_fdt                ),
    .clk_sys                  ( clk_sys                 ),
    .rstn_sys                 ( rstn_sys                ),
    .cache_ena                ( cache_ena               ),
    .cache_wena               ( cache_wena              ),
    .cache_addr               ( cache_addr              ),
    .cache_wdata              ( cache_wdata             ),
    .cache_rdata              ( cache_rdata             ),
    .coef_ena                 ( coef_ena                ),
    .coef_wena                ( coef_wena               ),
    .coef_addr                ( coef_addr               ),
    .coef_wdata               ( coef_wdata              ),
    .coef_rdata               ( coef_rdata              ),
    .rg_fdt_cache_spi_rw_en   ( rg_fdt_cache_spi_rw_en  ),
    .rg_fdt_coef_spi_rw_en    ( rg_fdt_coef_spi_rw_en   ),
    .fdtmem_rd                ( fdtmem_rd               ),
    .fdtmem_wr                ( fdtmem_wr               ),
    .fdtmem_addr              ( fdtmem_addr             ),
    .fdtmem_wdata             ( fdtmem_wdata            ),
    .fdtmem_rdata             ( fdtmem_rdata            ),
    .amp_cache_ena            ( amp_cache_ena           ),
    .amp_cache_wena           ( amp_cache_wena          ),
    .amp_cache_addr           ( amp_cache_addr          ),
    .amp_cache_wdata          ( amp_cache_wdata         ),
    .amp_cache_rdata          ( amp_cache_rdata         ),
    .norm_cache_ena           ( norm_cache_ena          ),
    .norm_cache_wena          ( norm_cache_wena         ),
    .norm_cache_addr          ( norm_cache_addr         ),
    .norm_cache_wdata         ( norm_cache_wdata        ),
    .norm_cache_rdata         ( norm_cache_rdata        ),
    .nn_cache_ena             ( nn_cache_ena            ),
    .nn_cache_wena            ( nn_cache_wena           ),
    .nn_cache_addr            ( nn_cache_addr           ),
    .nn_cache_wdata           ( nn_cache_wdata          ),
    .nn_cache_rdata           ( nn_cache_rdata          ),
    .nn_coef_ena              ( nn_coef_ena             ),
    .nn_coef_addr             ( nn_coef_addr            ),
    .nn_coef_rdata            ( nn_coef_rdata           ),
    .rg_fdt_en                ( rg_fdt_en               ),
    .rg_fdt_iq_calc_en        ( rg_fdt_iq_calc_en       ),
    .adc_data_in_vld          ( adc_data_in_vld         ),
    .amp_done                 ( amp_done                ),
    .amp_trig_norm            ( amp_trig_norm           ),
    .amp_mean_vld             ( amp_mean_vld            ),
    .norm_done                ( norm_done               ),
    .norm_trig_NN             ( norm_trig_NN            ),
    .NN_unit_done             ( NN_unit_done            ),
    .NN_unit_start            ( NN_unit_start           ),
    .amp_enable               ( amp_enable              ),
    .amp_iq_data_to_fifo_en   ( amp_iq_data_to_fifo_en  ),
    .norm_enable              ( norm_enable             ),
    .amp_working              ( amp_working             ),
    .norm_working             ( norm_working            ),
    .NN_working               ( NN_working              ),
    .rg_fdt_soft_clr          ( rg_fdt_soft_clr         ),
    .soft_clr                 ( soft_clr                ),
    .rg_fdt_wait_up           ( rg_fdt_wait_up          ),
    .rg_fdt_wait_down         ( rg_fdt_wait_down        ),
    .rg_fdt_auto_exit_en      ( rg_fdt_auto_exit_en     ),
    .dec_result               ( dec_result              ),
    .dec_result_vld           ( dec_result_vld          ),
    .fdt_up_int_sys           ( fdt_up_int_sys          ),
    .fdt_down_int_sys         ( fdt_down_int_sys        ),
    .fdt_auto_exit_pulse      ( fdt_auto_exit_pulse     ),
    .fdt_done_sys             ( fdt_done_sys            ),
    .amp_iq_vld_to_fifo       ( amp_iq_vld_to_fifo      ),
    .amp_iq_data_to_fifo      ( amp_iq_data_to_fifo     ),
    .amp_iq_vld_to_fifo_sys   ( amp_iq_vld_to_fifo_sys  ),
    .amp_iq_data_to_fifo_sys  ( amp_iq_data_to_fifo_sys )
);

amp_cal #(
    .FDT_ROW_N (FDT_ROW_N),
    .FDT_COL_N (FDT_COL_N)
) amp_cal_inst(
    .clk                         ( clk_fdt                    ),
    .rstn                        ( rstn_fdt                   ),
    .soft_clr                    ( soft_clr                   ),
    .rg_amp_therm_comp_ratio_0   ( rg_amp_therm_comp_ratio_0  ),
    .rg_amp_therm_comp_ratio_1   ( rg_amp_therm_comp_ratio_1  ),
    .rg_amp_therm_comp_ratio_2   ( rg_amp_therm_comp_ratio_2  ),
    .rg_amp_therm_comp_ratio_3   ( rg_amp_therm_comp_ratio_3  ),
    .rg_amp_therm_comp_ratio_4   ( rg_amp_therm_comp_ratio_4  ),
    .rg_amp_data_ratio           ( rg_amp_data_ratio          ),
    .rg_fifo_empty_dummy_en      ( rg_fifo_empty_dummy_en     ),
    .amp_enable                  ( amp_enable                 ),
    .amp_iq_data_to_fifo_en      ( amp_iq_data_to_fifo_en     ),
    .adc_data_in_vld             ( adc_data_in_vld            ),
    .adc0_data_in                ( adc0_data_in               ),
    .fdt_therm_comp_one_hot      ( fdt_therm_comp_one_hot     ),
    .amp_mean_vld                ( amp_mean_vld               ),
    .amp_mean                    ( amp_mean                   ),
    .amp_done                    ( amp_done                   ),
    .amp_trig_norm               ( amp_trig_norm              ),
    .cache_ena                   ( cache_ena                  ),
    .cache_wena                  ( cache_wena                 ),
    .cache_addr                  ( cache_addr                 ),
    .cache_wdata                 ( cache_wdata                ),
    .cache_rdata                 ( cache_rdata                ),
    .amp_iq_data_to_fifo         ( amp_iq_data_to_fifo        ),
    .amp_iq_vld_to_fifo          ( amp_iq_vld_to_fifo         )  
);

norm_cal norm_cal_inst(
    .clk                ( clk_fdt            ),
    .rstn               ( rstn_fdt           ),
    .rg_norm_data_ratio ( rg_norm_data_ratio ),
    .rg_fdt_tseq_num    ( rg_fdt_tseq_num    ),
    .norm_enable        ( norm_enable        ),
    .soft_clr           ( soft_clr           ),
    .amp_mean           ( amp_mean           ),
    .amp_mean_vld       ( amp_mean_vld       ),
    .norm_done          ( norm_done          ),
    .norm_trig_NN       ( norm_trig_NN       ),
    .cache_ena          ( cache_ena          ),
    .cache_wena         ( cache_wena         ),
    .cache_addr         ( cache_addr         ),
    .cache_wdata        ( cache_wdata        ),
    .cache_rdata        ( cache_rdata        )     
);

NN_unit NN_unit_inst(
    .clk                        ( clk_fdt                     ), 
    .rstn                       ( rstn_fdt                    ), 
    .rg_nn_ilayer_ih_data_ratio ( rg_nn_ilayer_ih_data_ratio  ), 
    .rg_nn_ilayer_hh_data_ratio ( rg_nn_ilayer_hh_data_ratio  ), 
    .rg_nn_hlayer_ih_data_ratio ( rg_nn_hlayer_ih_data_ratio  ), 
    .rg_nn_hlayer_hh_data_ratio ( rg_nn_hlayer_hh_data_ratio  ), 
    .rg_nn_flayer_data_ratio    ( rg_nn_flayer_data_ratio     ), 
    .rg_label_seq_init_en       ( rg_label_seq_init_en        ), 
    .rg_label_dec_mode          ( rg_label_dec_mode           ), 
    .rg_label_up_memcnt_th      ( rg_label_up_memcnt_th       ), 
    .rg_label_dn_memcnt_th      ( rg_label_dn_memcnt_th       ), 
    .rg_label_memseq_len        ( rg_label_memseq_len         ), 
    .ro_fdt_result_up           ( ro_fdt_result_up            ), 
    .ro_fdt_result_down         ( ro_fdt_result_down          ), 
    .soft_clr                   ( soft_clr                    ), 
    .coef_ena                   ( coef_ena                    ), 
    .coef_addr                  ( coef_addr                   ), 
    .coef_rdata                 ( coef_rdata                  ), 
    .cache_ena                  ( cache_ena                   ), 
    .cache_wena                 ( cache_wena                  ), 
    .cache_addr                 ( cache_addr                  ), 
    .cache_wdata                ( cache_wdata                 ), 
    .cache_rdata                ( cache_rdata                 ), 
    .NN_unit_start              ( NN_unit_start               ), 
    .NN_unit_done               ( NN_unit_done                ), 
    .dec_result                 ( dec_result                  ), 
    .dec_result_vld             ( dec_result_vld              )      
);

coef_cache_mem(
    .clk          ( clk_fdt     ),
    .rstn         ( rstn_fdt    ),
    .cache_ena    ( cache_ena   ),
    .cache_wena   ( cache_wena  ),
    .cache_addr   ( cache_addr  ),
    .cache_wdata  ( cache_wdata ),
    .cache_rdata  ( cache_rdata ),
    .coef_wena    ( coef_wena   ),
    .coef_addr    ( coef_addr   ),
    .coef_wdata   ( coef_wdata  ),
    .coef_rdata   ( coef_rdata  )    
);

endmodule