${PRJ_HOME}/0-rtl/top_lib/lp_soc_top.sv
${PRJ_HOME}/0-rtl/top_lib/digital_top.sv
${PRJ_HOME}/0-rtl/ip_pad_top/pad_top.sv
${PRJ_HOME}/0-rtl/ip_crgu/crgu.sv
${PRJ_HOME}/0-rtl/ip_pmu/pmu.sv
${PRJ_HOME}/0-rtl/ip_int_ctrl/int_ctrl.sv
${PRJ_HOME}/0-rtl/ip_spi_slave/spi_slave.sv
${PRJ_HOME}/0-rtl/ip_bus_mux/bus_mux.sv
${PRJ_HOME}/0-rtl/ip_spi_slave/spi_to_apb.sv
${PRJ_HOME}/0-rtl/ip_sync_fifo/sync_fifo.sv
${PRJ_HOME}/0-rtl/ip_time_ctrl/time_ctrl.sv
${PRJ_HOME}/0-rtl/ip_afe_ctrl/afe_ctrl.sv
${PRJ_HOME}/0-rtl/ip_isp/isp_ctrl.sv
${PRJ_HOME}/0-rtl/ip_isp/dpc.sv
${PRJ_HOME}/0-rtl/ip_reg/reg_top_apb_cfg.v
${PRJ_HOME}/0-rtl/ip_da_top/da_top.sv
${PRJ_HOME}/0-rtl/ip_da_top/analog_mux.sv

${PRJ_HOME}/0-rtl/ip_pad_top/pad_model.v
${PRJ_HOME}/0-rtl/ip_sync_fifo/reg_array.sv
${PRJ_HOME}/0-rtl/ip_da_top/analog_top.v

/home/jjt/projects/common_lib/sync/sync_level.sv
/home/jjt/projects/common_lib/sync/sync_pulse.sv
/home/jjt/projects/common_lib/sync/lp_pulse_sync.sv
/home/jjt/projects/common_lib/clk_gate/ckgate_cell.v
/home/jjt/projects/common_lib/div_clk/div_clk.sv
/home/jjt/projects/common_lib/sync_reset/sync_reset.sv
/home/jjt/projects/common_lib/clk_mux/clkmux.v
/home/jjt/library/tsmc40/common_lib/std_cell.v
////home/jjt/library/tsmc40/common_lib/tcbn40lpbwp12t40m1p_200a/tcbn40lpbwp12t40m1p.v
/home/jjt/library/tsmc40/tcbn40lpbwp12t40m1p_200a_vlg/TSMCHOME/digital/Front_End/verilog/tcbn40lpbwp12t40m1p_200a/tcbn40lpbwp12t40m1p.v
